package br.app.criati.financeiro.service;
import java.math.*; import java.time.*; import java.util.*;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import br.app.criati.empresa.model.Empresa; import br.app.criati.empresa.repository.EmpresaRepository; import br.app.criati.exception.*;
import br.app.criati.financeiro.model.*; import br.app.criati.financeiro.repository.*; import br.app.criati.financeiro.shared.model.*; import br.app.criati.financeiro.shared.repository.*;
import br.app.criati.shared.enums.*; import br.app.criati.tenant.ContextoEmpresaAtual; import br.app.criati.usuario.model.Usuario; import br.app.criati.usuario.repository.UsuarioRepository;
@Service public class CompraCartaoService {
 private final CompraCartaoRepository compras; private final CartaoCreditoRepository cartoes; private final CategoriaFinanceiraRepository categorias; private final PessoaFinanceiraRepository pessoas; private final ParteFinanceiraRepository partes; private final EmpresaRepository empresas; private final UsuarioRepository usuarios; private final ParcelamentoCartaoService parcelamento;
 public CompraCartaoService(CompraCartaoRepository a,CartaoCreditoRepository c,CategoriaFinanceiraRepository cat,PessoaFinanceiraRepository p,ParteFinanceiraRepository pf,EmpresaRepository e,UsuarioRepository u,ParcelamentoCartaoService par){compras=a;cartoes=c;categorias=cat;pessoas=p;partes=pf;empresas=e;usuarios=u;parcelamento=par;}
 @Transactional(readOnly=true) public List<CompraCartao> listar(ContextoEmpresaAtual ctx,UUID cartaoId,UUID titularId,UUID categoriaId,LocalDate competencia,StatusCompraCartao status,String busca){String termo=busca==null?"":busca.trim().toLowerCase(Locale.ROOT);return compras.findAllByEmpresaIdOrderByDataCompraDescCriadoEmDesc(ctx.empresaId()).stream().filter(c->cartaoId==null||c.getCartao().getId().equals(cartaoId)).filter(c->titularId==null||c.getPessoaResponsavel().getId().equals(titularId)).filter(c->categoriaId==null||c.getCategoria().getId().equals(categoriaId)).filter(c->status==null||c.getStatus()==status).filter(c->competencia==null||c.getParcelas().stream().anyMatch(p->p.getCompetencia().equals(competencia))).filter(c->termo.isBlank()||c.getDescricao().toLowerCase(Locale.ROOT).contains(termo)).toList();}
 @Transactional(readOnly=true) public CompraCartao buscar(UUID id,ContextoEmpresaAtual ctx){return compras.findByIdAndEmpresaId(id,ctx.empresaId()).orElseThrow(()->new DadosInvalidosException("Compra nao encontrada"));}
 @Transactional(readOnly=true) public ResumoComprasCartao resumir(ContextoEmpresaAtual ctx){List<CompraCartao> todas=compras.findAllByEmpresaIdOrderByDataCompraDescCriadoEmDesc(ctx.empresaId());List<CompraCartao> ativas=todas.stream().filter(c->c.getStatus()==StatusCompraCartao.ATIVA).toList();BigDecimal total=ativas.stream().map(CompraCartao::getValorTotal).reduce(BigDecimal.ZERO,BigDecimal::add).setScale(2);
  // CRIATI-FIN-015: totalTerceiros e somado independentemente (nao por subtracao) para que
  // totalResidencia+totalTerceiros==totalComprado sirva de checagem cruzada explicita nos
  // testes; ambos continuam incluidos em "total", que segue sendo o consumo real do limite.
  BigDecimal totalTerceiros=ativas.stream().filter(c->c.getParteFinanceira()!=null).map(CompraCartao::getValorTotal).reduce(BigDecimal.ZERO,BigDecimal::add).setScale(2);
  BigDecimal totalResidencia=total.subtract(totalTerceiros);
  List<CartaoCredito> principais=cartoes.findAllByEmpresaIdAndStatus(ctx.empresaId(),StatusCadastro.ATIVO).stream().filter(CartaoCredito::ehPrincipal).toList();BigDecimal limite=principais.stream().map(CartaoCredito::getLimiteTotal).reduce(BigDecimal.ZERO,BigDecimal::add).setScale(2);Map<UUID,BigDecimal> pessoasValores=new LinkedHashMap<>();Map<UUID,String> pessoasNomes=new LinkedHashMap<>();Map<UUID,BigDecimal> cartoesValores=new LinkedHashMap<>();Map<UUID,String> cartoesNomes=new LinkedHashMap<>();ativas.forEach(c->{pessoasValores.merge(c.getPessoaResponsavel().getId(),c.getValorTotal(),BigDecimal::add);pessoasNomes.put(c.getPessoaResponsavel().getId(),c.getPessoaResponsavel().getNome());cartoesValores.merge(c.getCartao().getId(),c.getValorTotal(),BigDecimal::add);cartoesNomes.put(c.getCartao().getId(),c.getCartao().getNome());});var porPessoa=pessoasValores.entrySet().stream().map(e->new ResumoComprasCartao.ValorPorPessoa(e.getKey(),pessoasNomes.get(e.getKey()),e.getValue())).toList();var porCartao=cartoesValores.entrySet().stream().map(e->new ResumoComprasCartao.ValorPorCartao(e.getKey(),cartoesNomes.get(e.getKey()),e.getValue())).toList();long parceladas=ativas.stream().filter(c->c.getQuantidadeParcelas()>1).count();long canceladas=todas.stream().filter(c->c.getStatus()==StatusCompraCartao.CANCELADA).count();return new ResumoComprasCartao(total,totalResidencia,totalTerceiros,limite,total,limite.subtract(total),ativas.size(),parceladas,canceladas,porPessoa,porCartao);}
 @Transactional public ResultadoCompra criar(UUID cartaoId,UUID pessoaId,UUID categoriaId,UUID parteId,String descricao,LocalDate data,BigDecimal valor,Integer qtd,String observacao,ContextoEmpresaAtual ctx){exigirAdmin(ctx);validar(descricao,data,valor,qtd);CartaoCredito usado=cartoes.findByIdAndEmpresaId(cartaoId,ctx.empresaId()).orElseThrow(CartaoCreditoNaoEncontradoException::new);CartaoCredito principal=usado.ehVirtual()?usado.getCartaoPrincipal():usado;principal=cartoes.findForUpdateByIdAndEmpresaId(principal.getId(),ctx.empresaId()).orElseThrow(CartaoCreditoNaoEncontradoException::new);if(!usado.estaAtivo()||!principal.estaAtivo())throw new DadosInvalidosException("Cartao inativo nao aceita compra");if(usado.estaBloqueadoEfetivo()||principal.estaBloqueadoEfetivo())throw new DadosInvalidosException("Cartao bloqueado nao aceita compra");PessoaFinanceira pessoa=pessoas.findByIdAndEmpresaId(pessoaId,ctx.empresaId()).filter(PessoaFinanceira::estaAtiva).orElseThrow(()->new DadosInvalidosException("Pessoa responsavel invalida"));CategoriaFinanceira categoria=categorias.findByIdAndEmpresaId(categoriaId,ctx.empresaId()).filter(CategoriaFinanceira::estaAtiva).orElseThrow(()->new DadosInvalidosException("Categoria invalida"));if(categoria.getTipo()!=TipoFinanceiro.DESPESA)throw new DadosInvalidosException("Compra exige categoria de despesa");ParteFinanceira parte=parteId==null?null:partes.findByIdAndEmpresaId(parteId,ctx.empresaId()).filter(ParteFinanceira::estaAtiva).orElseThrow(()->new DadosInvalidosException("Parte financeira invalida"));BigDecimal comprometido=comprometido(ctx.empresaId(),principal.getId());BigDecimal depois=comprometido.add(valor.setScale(2,RoundingMode.HALF_UP));if(depois.compareTo(principal.getLimiteTotal())>0)throw new DadosInvalidosException("Compra supera o limite total disponivel");Usuario autor=usuarios.findById(ctx.usuarioId()).orElseThrow(UsuarioNaoEncontradoException::new);Empresa empresa=empresas.findById(ctx.empresaId()).orElseThrow(EmpresaNaoEncontradaException::new);CompraCartao compra=new CompraCartao(empresa,usado,principal,pessoa,categoria,parte,descricao.trim(),data,valor.setScale(2,RoundingMode.HALF_UP),qtd,normalizar(observacao),autor);List<BigDecimal> valores=parcelamento.dividir(valor,qtd);LocalDate primeira=parcelamento.primeiraCompetencia(data,principal.getDiaFechamento(),principal.getDiaVencimento());List<LocalDate> competencias=parcelamento.competencias(primeira,qtd);for(int i=0;i<qtd;i++)compra.adicionarParcela(new ParcelaCompraCartao(empresa,compra,i+1,qtd,valores.get(i),competencias.get(i),autor));compras.save(compra);boolean alerta=principal.getLimiteSaudavel()!=null&&depois.compareTo(principal.getLimiteSaudavel())>0;return new ResultadoCompra(compra,comprometido,depois,principal.getLimiteTotal().subtract(depois),alerta);}
 @Transactional public CompraCartao cancelar(UUID id,String motivo,ContextoEmpresaAtual ctx){exigirAdmin(ctx);CompraCartao c=buscar(id,ctx);validarMotivo(motivo);c.cancelar(motivo.trim(),autor(ctx));return c;}
 @Transactional public CompraCartao estornar(UUID id,String motivo,ContextoEmpresaAtual ctx){exigirAdmin(ctx);CompraCartao c=buscar(id,ctx);validarMotivo(motivo);c.estornar(motivo.trim(),autor(ctx));return c;}
 @Transactional(readOnly=true) public BigDecimal comprometido(UUID empresaId,UUID principalId){BigDecimal v=compras.somarComprometido(empresaId,principalId,StatusCompraCartao.ATIVA);return (v==null?BigDecimal.ZERO:v).setScale(2,RoundingMode.HALF_UP);}
 private void validar(String d,LocalDate data,BigDecimal v,Integer q){if(d==null||d.isBlank()||d.trim().length()>200)throw new DadosInvalidosException("Descricao invalida");if(data==null)throw new DadosInvalidosException("Data da compra e obrigatoria");if(v==null||v.signum()<=0)throw new DadosInvalidosException("Valor total deve ser maior que zero");if(q==null||q<1)throw new DadosInvalidosException("Quantidade de parcelas deve ser ao menos uma");}
 private void validarMotivo(String m){if(m==null||m.isBlank()||m.trim().length()>500)throw new DadosInvalidosException("Motivo e obrigatorio e deve possuir ate 500 caracteres");}
 private Usuario autor(ContextoEmpresaAtual c){return usuarios.findById(c.usuarioId()).orElseThrow(UsuarioNaoEncontradoException::new);} private void exigirAdmin(ContextoEmpresaAtual c){if(c.perfil()!=PerfilUsuario.ADMINISTRADOR)throw new AcessoNegadoException();} private String normalizar(String s){return s==null||s.isBlank()?null:s.trim();}
 public record ResultadoCompra(CompraCartao compra,BigDecimal limiteAntes,BigDecimal limiteDepois,BigDecimal limiteDisponivel,boolean alertaLimiteSaudavel){}
}
